/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package poc_dependencies_gradle_plugin_consumer;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
